### ISSUE TITLE
Add ability to add and reset password

### ISSUE THREAD

**Issue by ajatprabha** [devlup-labs/gymkhana_portal#20]
## Issue
Not able to use password-based login after introducing Google Oauth2.0

## Description
After adding Google Oauth2.0 based sign-in feature, new users don't set a password to their accounts.

## Expected
Users should be given a choice to set a password if their account was created using Google Oauth2.0 client. They should also be able to reset their password and ask for a forgot password reset URL

### Changes [Required]
- [ ] [Create new view to set password]
- [ ] [Create new view to request password reset URL]
- [ ] [Update existing views if necessary]

**Comment by Sanji515** [comment]
I want to do this issue, Please assign this to me.

**Comment by ajatprabha** [comment]
@Sanji515 You may work on it!

**Comment by Sanji515** [comment]
Hello Sir,
I'm new to this, please help me....I have cloned your gymkhana_portal and did all things which were told on 'readme' file but still getting errors on running 'makemigrations'. Please find the screenshot of that error below…. HELP ME!!!


Sent from Mail for Windows 10
