### ISSUE TITLE
UI bug fixes in contact card

### ISSUE THREAD

**Issue by shashankmohabia** [devlup-labs/gymkhana_portal#25]
## Issue
Overflow in the contact cards for more than single line in card block paragraph.

## Description
Currently on https://students.iitj.ac.in/office-bearers/ there is an overflow in some of the contact cards mainly due to large length of society names of the office bearers.

## Expected
There shall be no overflow and all the positions of the different components of the contact card should be fixed preferably.

### Changes [Required]
- Ensure that there is no overflow.
- Keep the positions fixed for different components in the contact card if possible.
- Limit the size of the name of the society to a maximum of 80 characters so as to avoid more than two lines in card block paragraph.

**Comment by garglakshya18** [comment]
I am taking up this issue.
