### ISSUE TITLE
Remove secret key from .env.example

### ISSUE THREAD

**Issue by hirenchalodiya1** [devlup-labs/gymkhana_portal#54]
## Issue
- Remove a secret key from the `.env.example` file as it may affect security.

## Expected
- The secret key should not be public.
## Actual
- The environment file contains a secret key.

### Changes
- Remove the secret key from the environment file.
- Add a secret key in the Travis environment.
- Add a secret key in the GitHub workflow environment.

**Comment by anshulahuja98** [comment]
That's a dummy key
It's alright
